FROM base:1.0

ENV DEBIAN_FRONTEND="noninteractive"

RUN curl -L https://github.com/ancwrd1/snx-rs/releases/download/v3.1.1/snx-rs-v3.1.1-linux-x86_64.tar.xz -o /opt/snx-rs-v3.1.1-linux-x86_64.tar.xz && \
    tar axf /opt/snx-rs-v3.1.1-linux-x86_64.tar.xz -C /opt/ && mv /opt/snx-rs-v3.1.1-linux-x86_64 /opt/snx-rs && rm /opt/snx-rs-*

COPY .config /root/.config
COPY --chmod=755 snx-rs.sh /opt/snx-rs

ENTRYPOINT ["/opt/snx-rs/snx-rs.sh"]
