#!/bin/sh
touch /root/.Xauthority
/usr/bin/Xorg -noreset +extension GLX +extension RANDR +extension RENDER -auth /root/.Xauthority -config /etc/X11/xorg.conf $DISPLAY &
xauth -f /root/.Xauthority generate $DISPLAY . trusted
exec /opt/vdi-client/bin/desktop-client &
/usr/bin/x11vnc -display $DISPLAY -noxdamage -env FD_XDM=1 -auth /root/.Xauthority -forever "$@"
